name: Compilar APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Build APK Release com SDK 36
        run: flutter build apk --release --no-tree-shake-icons --build-number=1 --extra-gen-snapshot-options=--enable-asserts || true
        
      - name: Compilar via Gradle Forçando SDK 36
        run: |
          cd android
          ./gradlew assembleRelease -PcompileSdkVersion=36 -PtargetSdkVersion=36

      - name: Salvar APK nos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
