name: Compilar APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recriar estrutura Android
        run: |
          rm -rf android
          flutter create . --org com.concursoweb --project-name concurso_app --platforms android

      - name: Forçar SDK 36 em TODOS os subprojetos e plugins
        run: |
          cat << 'EOF' >> android/build.gradle

          subprojects {
              afterEvaluate { project ->
                  if (project.hasProperty('android')) {
                      project.android {
                          compileSdkVersion 36
                      }
                  }
              }
          }
          EOF

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --no-tree-shake-icons

      - name: Salvar APK nos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: '**/build/app/outputs/flutter-apk/*.apk'
